#!/usr/bin/env bash
#Print "Best School" 10 times using an until loop
i=0
until [ $i -eq 10 ]
do
	echo "Best School"
	i=$((i+1))
done
Footer
© 2023 GitHub, Inc.
Footer navigation
Terms
Privacy
Securit
